// lib/library-styles.ts — Library UI 内联样式(从 tabs/library.tsx 迁出)
// 纯函数: theme → CSSProperties 映射。迁移自 library.tsx,逻辑零改动。
import type { CSSProperties } from "react"
import type { ThemeTokens } from "./design-tokens"

export const makeStyles = (theme: ThemeTokens): Record<string, CSSProperties> => {
  // M5 Task 5:用 theme.* 替代硬编码 rgba,light 主题下不会失效
  const card = theme.card
  const cardHover = theme.cardHover
  const textTertiary = theme.textTertiary
  const textSecondary = theme.textSecondary
  const hairline = theme.hairline
  const green = "#30d158" // success 状态色,design-tokens 暂无对应,保留字面量

  return {
    shell: {
      width: "100vw",
      height: "100vh",
      display: "flex",
      overflow: "hidden",
      background: theme.bg,
      color: theme.textPrimary,
    },
    sidebar: {
      width: 248,
      flexShrink: 0,
      background: "#0d0d0f",
      borderRight: `1px solid ${theme.hairline}`,
      display: "flex",
      flexDirection: "column",
      padding: "20px 14px",
    },
    brand: {
      display: "flex",
      alignItems: "center",
      gap: 10,
      padding: "4px 8px 20px",
    },
    logo: {
      width: 30,
      height: 30,
      borderRadius: theme.r.sm,
      background: `linear-gradient(135deg, ${theme.accentLight}, ${theme.accent})`,
      display: "grid",
      placeItems: "center",
      boxShadow: "0 4px 12px rgba(10,132,255,0.4)",
      flexShrink: 0,
    },
    brandName: {
      fontSize: 16,
      fontWeight: 700,
      letterSpacing: -0.3,
      lineHeight: 1.05,
    },
    brandSub: {
      display: "block",
      fontSize: 10,
      fontWeight: 500,
      color: textTertiary,
      letterSpacing: 0.5,
      marginTop: 1,
    },
    sidebarGroup: {
      marginTop: 18,
      display: "flex",
      flexDirection: "column",
      gap: 2,
    },
    sidebarGroupHead: {
      fontSize: 11,
      fontWeight: 600,
      color: textTertiary,
      letterSpacing: 0.5,
      padding: "0 8px 8px",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
    },
    sidebarAction: {
      border: "none",
      background: "transparent",
      color: theme.textTertiary,
      cursor: "pointer",
      padding: 0,
      fontSize: 11,
    },
    sidebarItem: {
      border: "none",
      background: "transparent",
      color: "rgba(255,255,255,0.68)",
      borderRadius: theme.r.sm,
      padding: "8px 9px",
      display: "flex",
      alignItems: "center",
      gap: 10,
      cursor: "pointer",
      textAlign: "left",
      transition: `background ${theme.durFast} ${theme.easeOut}, color ${theme.durFast} ${theme.easeOut}`,
    },
    sidebarItemActive: {
      background: "rgba(10,132,255,0.16)",
      color: "#4da3ff",
      fontWeight: 600,
    },
    sidebarLabel: {
      flex: 1,
      minWidth: 0,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      fontSize: 13.5,
    },
    sidebarCount: {
      marginLeft: "auto",
      fontSize: 11,
      color: textTertiary,
      fontWeight: 600, // M5 Task 5:数字标签用 600(更醒目)
    },
    sidebarActions: {
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      marginLeft: 8,
    },
    sidebarMini: {
      fontSize: 10,
      color: textTertiary,
      border: `1px solid ${theme.hairlineSoft}`,
      borderRadius: theme.r.xs,
      padding: "2px 5px",
      lineHeight: 1,
      flexShrink: 0,
    },
    sidebarEmpty: {
      fontSize: 11,
      color: textTertiary,
      padding: "4px 8px 2px",
    },
    dot: {
      width: 9,
      height: 9,
      borderRadius: theme.r.pill,
      flexShrink: 0,
    },
    main: {
      flex: 1,
      minWidth: 0,
      display: "flex",
      flexDirection: "column",
      position: "relative",
      background: "radial-gradient(ellipse 60% 40% at 20% 0%, rgba(120,80,255,0.06), transparent 60%), #141416",
    },
    toolbar: {
      padding: "18px 28px",
      display: "flex",
      alignItems: "center",
      gap: 14,
      // M5 Task 6:窄宽允许换行,避免标题/搜索框被挤
      flexWrap: "wrap",
      borderBottom: `1px solid ${theme.hairline}`,
      flexShrink: 0,
    },
    title: {
      margin: 0,
      fontSize: 22,
      fontWeight: 700,
      letterSpacing: -0.5,
      lineHeight: 1.1,
      minWidth: 92,
    },
    searchWrap: {
      flex: 1,
      minWidth: 220, // M5 Task 6:防止窄宽时搜索框被压成 0
      maxWidth: 420,
      position: "relative",
    },
    searchInput: {
      width: "100%",
      background: card,
      border: "1px solid transparent",
      borderRadius: theme.r.pill,
      padding: "9px 14px 9px 38px",
      color: theme.textPrimary,
      fontSize: 13.5,
      outline: "none",
      transition: `all ${theme.durFast} ${theme.easeOut}`,
    },
    searchIcon: {
      position: "absolute",
      left: 13,
      top: "50%",
      transform: "translateY(-50%)",
      color: textTertiary,
      pointerEvents: "none",
    },
    toolbarSpacer: { flex: 1 },
    toolbarButton: {
      border: "none",
      background: card,
      color: "rgba(255,255,255,0.68)",
      borderRadius: theme.r.sm,
      padding: "9px 13px",
      fontSize: 13,
      fontWeight: 600, // M5 Task 5:工具按钮用 600
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      gap: 7,
      whiteSpace: "nowrap",
    },
    // M6 Task 4:导出历史按钮 alert 态(有失败项时)
    toolbarButtonAlert: {
      color: theme.danger ?? "#FF453A",
    },
    toolbarBadge: {
      fontSize: 11,
      fontWeight: 600,
      color: textTertiary,
      background: "rgba(255,255,255,0.10)",
      borderRadius: theme.r.pill,
      padding: "1px 6px",
      minWidth: 18,
      textAlign: "center",
    },
    toolbarBadgeAlert: {
      fontSize: 11,
      fontWeight: 700,
      color: "#fff",
      background: theme.danger ?? "#FF453A",
      borderRadius: theme.r.pill,
      padding: "0 5px",
      minWidth: 16,
      textAlign: "center",
    },
    // M6 Task 4:导出历史 modal
    historyItem: {
      padding: "12px 0",
      borderBottom: `0.5px solid ${theme.hairline}`,
    },
    historyItemHead: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 6,
    },
    historyTime: {
      fontSize: 12,
      color: textTertiary,
    },
    historyStatus: {
      fontSize: 12,
      fontWeight: 600,
      padding: "2px 8px",
      borderRadius: theme.r.pill,
    },
    historyStatusOk: {
      color: "#30d158",
      background: "rgba(48,209,88,0.15)",
    },
    historyStatusPartial: {
      color: "#FF9F0A",
      background: "rgba(255,159,10,0.15)",
    },
    historyFolders: {
      display: "flex",
      flexWrap: "wrap",
      gap: 6,
      marginBottom: 6,
    },
    historyFolder: {
      fontSize: 11,
      color: textSecondary,
      background: card,
      border: `0.5px solid ${theme.hairline}`,
      borderRadius: theme.r.pill,
      padding: "2px 8px",
    },
    historyFailed: {
      marginTop: 6,
      padding: 8,
      background: "rgba(255,69,58,0.08)",
      border: `0.5px solid rgba(255,69,58,0.3)`,
      borderRadius: theme.r.sm,
    },
    historyFailedItem: {
      display: "flex",
      justifyContent: "space-between",
      fontSize: 11,
      color: textSecondary,
      marginBottom: 2,
    },
    historyFailedName: {
      flex: 1,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    historyFailedError: {
      color: theme.danger ?? "#FF453A",
      marginLeft: 8,
    },
    historyFailedMore: {
      fontSize: 11,
      color: textTertiary,
      marginTop: 4,
    },
    historyRetryBtn: {
      marginTop: 8,
      padding: "5px 12px",
      fontSize: 12,
      fontWeight: 600,
      color: "#fff",
      background: theme.accent,
      border: "none",
      borderRadius: theme.r.sm,
      cursor: "pointer",
    },
    viewToggle: {
      display: "flex",
      background: card,
      borderRadius: theme.r.sm,
      padding: 2,
    },
    viewButton: {
      border: "none",
      background: "transparent",
      color: textTertiary,
      width: 30,
      height: 28,
      borderRadius: 6,
      cursor: "pointer",
      display: "grid",
      placeItems: "center",
    },
    viewButtonActive: {
      background: "rgba(255,255,255,0.14)",
      color: "#fff",
    },
    dashboard: {
      display: "grid",
      // M5 Task 6:auto-fit 自适应列数 — 1024+ 4 列,700-1024 2-3 列,<700 单列
      gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
      gap: 12,
      padding: "18px 28px 4px",
      flexShrink: 0,
    },
    dashCard: {
      background: card,
      border: `1px solid ${theme.hairlineSoft}`,
      borderRadius: theme.r.md,
      padding: "14px 16px",
      position: "relative",
      overflow: "hidden",
      minWidth: 0,
    },
    dashLabel: {
      fontSize: 12,
      color: textTertiary,
      display: "flex",
      alignItems: "center",
      gap: 6,
    },
    dashValue: {
      fontSize: 26,
      fontWeight: 700,
      letterSpacing: -0.6,
      marginTop: 6,
      lineHeight: 1,
    },
    dashUnit: {
      fontSize: 13,
      fontWeight: 500,
      color: textTertiary,
      marginLeft: 3,
    },
    dashHint: {
      fontSize: 11,
      marginTop: 5,
      color: textTertiary,
      fontWeight: 600,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    positiveHint: { color: green },
    subbar: {
      padding: "14px 28px",
      display: "flex",
      alignItems: "center",
      gap: 10,
      // M5 Task 6:窄宽让筛选 chip 与批量操作换行,避免重叠
      flexWrap: "wrap",
      flexShrink: 0,
    },
    chip: {
      fontSize: 12.5,
      fontWeight: 500,
      color: "rgba(255,255,255,0.68)",
      background: card,
      border: "none",
      padding: "6px 12px",
      borderRadius: theme.r.pill,
      cursor: "pointer",
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      height: 30,
    },
    chipActive: {
      color: "#fff",
      background: theme.accent,
    },
    chipXhsActive: {
      color: "#fff",
      background: theme.xhs,
    },
    bulkRight: {
      marginLeft: "auto",
      display: "flex",
      alignItems: "center",
      gap: 10,
    },
    // M6 Task 2.6:渐进渲染计数 — 弱化色调,避免与"已选 N 项"主操作抢视觉
    subbarCount: {
      fontSize: 12,
      fontWeight: 500,
      color: textTertiary,
      whiteSpace: "nowrap",
    },
    selectedText: {
      fontSize: 13,
      color: "rgba(255,255,255,0.68)",
      whiteSpace: "nowrap",
    },
    bulkGhost: {
      border: "none",
      borderRadius: theme.r.sm,
      padding: "8px 15px",
      fontSize: 13,
      fontWeight: 600,
      cursor: "pointer",
      display: "inline-flex",
      alignItems: "center",
      gap: 7,
      background: card,
      color: "rgba(255,255,255,0.68)",
      whiteSpace: "nowrap",
    },
    bulkGhostActive: {
      background: "rgba(10,132,255,0.16)",
      color: "#4da3ff",
    },
    bulkPrimary: {
      border: "none",
      borderRadius: theme.r.sm,
      padding: "8px 15px",
      fontSize: 13,
      fontWeight: 600,
      cursor: "pointer",
      display: "inline-flex",
      alignItems: "center",
      gap: 7,
      background: theme.accent,
      color: "#fff",
      boxShadow: "0 4px 14px rgba(10,132,255,0.35)",
      whiteSpace: "nowrap",
    },
    bulkDanger: {
      border: "none",
      borderRadius: theme.r.sm,
      padding: 8,
      width: 33,
      height: 33,
      fontSize: 13,
      fontWeight: 600,
      cursor: "pointer",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      background: theme.dangerBg,
      color: theme.danger,
    },
    disabled: {
      opacity: 0.42,
      cursor: "default",
      boxShadow: "none",
    },
    content: {
      flex: 1,
      overflowY: "auto",
      padding: "4px 28px 40px",
      minHeight: 0,
    },
    timeSection: {
      marginBottom: 18,
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: 600,
      color: textTertiary,
      letterSpacing: 0.3,
      margin: "18px 0 12px",
      display: "flex",
      alignItems: "center",
      gap: 8,
    },
    sectionPartial: {
      fontSize: 11,
      fontWeight: 400,
      color: `${textTertiary}99`,
    },
    loadMoreWrap: {
      display: "flex",
      justifyContent: "center",
      padding: "16px 0 8px",
    },
    loadMoreBtn: {
      background: card,
      color: textSecondary,
      border: `0.5px solid ${hairline}`,
      borderRadius: 10,
      padding: "8px 20px",
      fontSize: 13,
      fontWeight: 500,
      cursor: "pointer",
      fontFamily: "inherit",
    },
    grid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fill, minmax(150px, 1fr))",
      gap: 14,
    },
    cell: {
      position: "relative",
      aspectRatio: "1",
      borderRadius: theme.r.md,
      overflow: "hidden",
      background: card,
      cursor: "pointer",
      transition: `transform ${theme.durFast} ${theme.easeOut}, box-shadow ${theme.durFast} ${theme.easeOut}`,
    },
    cellSelected: {
      outline: `3px solid ${theme.accent}`,
      outlineOffset: -3,
    },
    cellSelectedFrame: {
      position: "absolute",
      inset: 0,
      border: `3px solid ${theme.accent}`,
      borderRadius: theme.r.md,
      boxShadow: "inset 0 0 0 1px rgba(255,255,255,0.16)",
      pointerEvents: "none",
      zIndex: 4,
    },
    cellImage: {
      position: "absolute",
      inset: 0,
      width: "100%",
      height: "100%",
      objectFit: "cover",
      display: "block",
    },
    mediaPlaceholder: {
      position: "absolute",
      inset: 0,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      background: "linear-gradient(145deg, rgba(46,46,50,0.96), rgba(18,18,20,0.98))",
      color: "rgba(255,255,255,0.62)",
      fontSize: 12,
      fontWeight: 600,
    },
    mediaBadge: {
      position: "absolute",
      top: 8,
      left: 8,
      fontSize: 11,
      fontWeight: 700,
      color: "#fff",
      background: "rgba(0,0,0,0.55)",
      backdropFilter: "blur(6px)",
      WebkitBackdropFilter: "blur(6px)",
      padding: "3px 8px",
      borderRadius: theme.r.pill,
      display: "flex",
      alignItems: "center",
      gap: 4,
    },
    platformDot: {
      position: "absolute",
      top: 8,
      left: 8,
      width: 7,
      height: 7,
      borderRadius: theme.r.pill,
    },
    videoBadge: {
      position: "absolute",
      bottom: 8,
      right: 8,
      width: 24,
      height: 24,
      borderRadius: theme.r.pill,
      background: "rgba(0,0,0,0.5)",
      backdropFilter: "blur(6px)",
      WebkitBackdropFilter: "blur(6px)",
      display: "grid",
      placeItems: "center",
      color: "#fff",
    },
    previewAction: {
      position: "absolute",
      top: 8,
      right: 38,
      width: 28,
      height: 28,
      borderRadius: theme.r.pill,
      border: "1px solid rgba(255,255,255,0.22)",
      background: "rgba(0,0,0,0.46)",
      backdropFilter: "blur(8px)",
      WebkitBackdropFilter: "blur(8px)",
      color: "#fff",
      cursor: "pointer",
      display: "grid",
      placeItems: "center",
      padding: 0,
      zIndex: 2,
      boxShadow: "0 4px 12px rgba(0,0,0,0.26)",
    },
    check: {
      position: "absolute",
      top: 8,
      right: 8,
      width: 22,
      height: 22,
      borderRadius: theme.r.pill,
      border: "2px solid rgba(255,255,255,0.85)",
      background: "rgba(0,0,0,0.25)",
      backdropFilter: "blur(4px)",
      WebkitBackdropFilter: "blur(4px)",
      opacity: 1,
      transition: `all ${theme.durFast} ${theme.easeOut}`,
      display: "grid",
      placeItems: "center",
      color: "#fff",
      cursor: "pointer",
      padding: 0,
      zIndex: 5,
    },
    checkActive: {
      opacity: 1,
      background: theme.accent,
      // M6 Task 3 修复:用完整 border 简写,避免与 check.border (shorthand) 冲突
      // 原 borderColor 单写属性在 rerender 时被 React 移除,导致选中态边框颜色错乱
      border: `2px solid ${theme.accent}`,
      color: "#fff",
    },
    cellInfo: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      padding: "22px 10px 9px",
      background: "linear-gradient(transparent, rgba(0,0,0,0.78))",
      opacity: 0,
      transition: `opacity ${theme.durFast} ${theme.easeOut}`,
      pointerEvents: "none",
    },
    cellAuthor: {
      fontSize: 11.5,
      fontWeight: 600,
      color: "#fff",
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
    cellActions: {
      display: "flex",
      gap: 6,
      marginTop: 7,
      pointerEvents: "auto",
    },
    miniAction: {
      width: 26,
      height: 26,
      borderRadius: 7,
      background: "rgba(255,255,255,0.16)",
      backdropFilter: "blur(8px)",
      WebkitBackdropFilter: "blur(8px)",
      border: "none",
      cursor: "pointer",
      display: "grid",
      placeItems: "center",
      color: "#fff",
    },
    list: {
      display: "flex",
      flexDirection: "column",
      gap: 8,
      paddingTop: 10,
    },
    row: {
      minHeight: 64,
      borderRadius: theme.r.md,
      background: card,
      border: `1px solid ${theme.hairlineSoft}`,
      display: "grid",
      gridTemplateColumns: "34px 48px minmax(0, 1fr) 110px",
      alignItems: "center",
      gap: 12,
      padding: "8px 12px",
    },
    rowSelected: {
      // M6 Task 3 修复:用完整 border 简写,避免与 row.border (shorthand) 冲突
      border: `1px solid ${theme.accent}`,
      background: "rgba(10,132,255,0.10)",
    },
    rowCheck: {
      width: 22,
      height: 22,
      borderRadius: theme.r.pill,
      border: "2px solid rgba(255,255,255,0.55)",
      background: "transparent",
      color: "#fff",
      display: "grid",
      placeItems: "center",
      cursor: "pointer",
      padding: 0,
    },
    rowThumbButton: {
      width: 48,
      height: 48,
      border: "none",
      padding: 0,
      borderRadius: theme.r.sm,
      overflow: "hidden",
      background: cardHover,
      cursor: "pointer",
    },
    rowThumb: {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      display: "block",
    },
    rowPlaceholder: {
      width: "100%",
      height: "100%",
      display: "grid",
      placeItems: "center",
      background: "linear-gradient(145deg, rgba(46,46,50,0.96), rgba(18,18,20,0.98))",
      color: "rgba(255,255,255,0.62)",
    },
    rowMeta: {
      minWidth: 0,
      textAlign: "left",
      border: "none",
      background: "transparent",
      color: theme.textPrimary,
      cursor: "pointer",
      display: "flex",
      flexDirection: "column",
      gap: 4,
    },
    rowTitle: {
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      fontSize: 13,
      fontWeight: 600,
    },
    rowSub: {
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      fontSize: 12,
      color: textTertiary,
    },
    rowDate: {
      fontSize: 12,
      color: textTertiary,
      textAlign: "right",
    },
    // M5 Task 3:空状态视觉分两档(大:全库无素材 / 小:筛选无结果)
    emptyLarge: {
      height: "100%",
      minHeight: 360,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      padding: 24,
    },
    emptySmall: {
      height: "100%",
      minHeight: 240,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      padding: 24,
      gap: 6,
    },
    emptyIllust: {
      width: 72,
      height: 72,
      borderRadius: theme.r.md,
      background: theme.card,
      border: `0.5px solid ${theme.hairline}`,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: theme.textSecondary,
      marginBottom: theme.sp.md,
    },
    emptyTitle: {
      fontSize: 17,
      fontWeight: 600,
      letterSpacing: -0.2,
      color: theme.textPrimary,
      marginBottom: 4,
    },
    emptySub: {
      fontSize: 13,
      color: textTertiary,
      lineHeight: 1.5,
      maxWidth: 420,
    },
    emptyAction: {
      marginTop: theme.sp.md,
      height: 34,
      padding: "0 16px",
      border: "none",
      borderRadius: theme.r.sm,
      background: theme.accent,
      color: "#fff",
      fontWeight: 600,
      fontSize: 13,
      cursor: "pointer",
    },
    dialogOverlay: {
      position: "fixed",
      inset: 0,
      zIndex: 130,
      background: "rgba(0,0,0,0.48)",
      backdropFilter: theme.glassBlur,
      WebkitBackdropFilter: theme.glassBlur,
      display: "grid",
      placeItems: "center",
      padding: 24,
    },
    dialog: {
      width: 360,
      maxWidth: "100%",
      background: "rgba(40,40,42,0.96)",
      border: `1px solid ${theme.hairline}`,
      borderRadius: theme.r.lg,
      boxShadow: theme.shadowFloat,
      padding: 16,
      color: "#fff",
    },
    dialogHead: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 14,
    },
    dialogTitle: {
      fontSize: 17,
      fontWeight: 700,
      letterSpacing: -0.3,
    },
    dialogClose: {
      width: 28,
      height: 28,
      borderRadius: theme.r.pill,
      border: "none",
      background: card,
      color: theme.textSecondary,
      cursor: "pointer",
      display: "grid",
      placeItems: "center",
      fontSize: 18,
      lineHeight: 1,
    },
    dialogInput: {
      width: "100%",
      height: 38,
      border: `1px solid ${theme.hairline}`,
      background: card,
      color: "#fff",
      borderRadius: theme.r.sm,
      padding: "0 12px",
      outline: "none",
      marginBottom: 12,
    },
    colorGrid: {
      display: "flex",
      gap: 8,
      marginBottom: 14,
    },
    colorButton: {
      width: 26,
      height: 26,
      borderRadius: theme.r.pill,
      border: "2px solid transparent",
      cursor: "pointer",
    },
    colorButtonActive: {
      // M6 Task 3 修复:用完整 border 简写,避免与 colorButton.border (shorthand) 冲突
      border: "2px solid #fff",
      boxShadow: `0 0 0 2px ${theme.accent}`,
    },
    dialogPrimary: {
      width: "100%",
      height: 36,
      border: "none",
      borderRadius: theme.r.sm,
      background: theme.accent,
      color: "#fff",
      fontWeight: 600,
      cursor: "pointer",
    },
    // M6 Task 5:置顶 toggle 行
    pinRow: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      fontSize: 13,
      color: textSecondary,
      cursor: "pointer",
    },
    collectionList: {
      display: "flex",
      flexDirection: "column",
      gap: 8,
    },
    collectionChoice: {
      height: 38,
      border: `1px solid ${theme.hairlineSoft}`,
      borderRadius: theme.r.sm,
      background: card,
      color: "#fff",
      display: "flex",
      alignItems: "center",
      gap: 10,
      padding: "0 12px",
      cursor: "pointer",
      textAlign: "left",
    },
    dialogEmpty: {
      padding: "18px 8px",
      textAlign: "center",
      color: textTertiary,
      fontSize: 13,
    },
    dialogBody: {
      color: theme.textSecondary,
      fontSize: 13,
      lineHeight: 1.5,
      marginBottom: 14,
    },
    dialogActions: {
      display: "flex",
      justifyContent: "flex-end",
      gap: 8,
    },
    dialogGhost: {
      height: 34,
      border: "none",
      borderRadius: theme.r.sm,
      background: card,
      color: theme.textSecondary,
      padding: "0 14px",
      cursor: "pointer",
    },
    dialogDanger: {
      height: 34,
      border: "none",
      borderRadius: theme.r.sm,
      background: theme.dangerBg,
      color: theme.danger,
      padding: "0 14px",
      cursor: "pointer",
      fontWeight: 600,
    },
    toast: {
      position: "fixed",
      bottom: 24,
      left: "50%",
      transform: "translateX(-50%)",
      background: "rgba(40,40,42,0.92)",
      backdropFilter: "blur(30px)",
      WebkitBackdropFilter: "blur(30px)",
      border: `1px solid ${theme.hairline}`,
      borderRadius: theme.r.md,
      padding: "12px 18px",
      display: "flex",
      alignItems: "center",
      gap: 14,
      boxShadow: theme.shadowFloat,
      fontSize: 13,
      zIndex: 120,
      color: "#fff",
    },
    toastIcon: {
      width: 22,
      height: 22,
      borderRadius: theme.r.pill,
      background: green,
      color: "#062a10",
      display: "grid",
      placeItems: "center",
      flexShrink: 0,
    },
    toastIconError: {
      background: theme.danger,
      color: "#fff",
    },
    toastText: {
      whiteSpace: "nowrap",
    },
    toastAction: {
      border: "none",
      background: "transparent",
      color: theme.accent,
      fontWeight: 600,
      cursor: "pointer",
      padding: 0,
    },
  }
}
